//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorClientProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Client : INotifyPropertyChanged
    {
        private int partyId;
        private int partyCode;
        private string fullName;
        private int taxCode;
        private string countryCode;
        private DateTime registrationDate;
        private string clientType;

        public int PartyId { get => partyId; set { partyId = value; OnPropertyChanged(nameof(partyId)); } }
        public int PartyCode { get => partyCode; set { partyCode = value; OnPropertyChanged(nameof(partyCode)); } }
        public string FullName { get => fullName; set { fullName = value; OnPropertyChanged(nameof(fullName)); } }
        public int TaxCode { get => taxCode; set { taxCode = value; OnPropertyChanged(nameof(taxCode)); } }
        public string CountryCode { get => countryCode; set { countryCode = value; OnPropertyChanged(nameof(countryCode)); } }
        public System.DateTime RegistrationDate { get => registrationDate; set { registrationDate = value; OnPropertyChanged(nameof(registrationDate)); } }
        public string ClientType { get => clientType; set { clientType = value; OnPropertyChanged(nameof(clientType)); } }

        //Records

        private ObservableCollection<Client> _clientRecords;
        public ObservableCollection<Client> ClientRecords
        {
            get
            {
                return _clientRecords;
            }
            set
            {
                _clientRecords = value;
                OnPropertyChanged("ClientRecords");
            }
        }

        private void ClientModel_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            OnPropertyChanged("ClientRecords");
        }
        //

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
